---
jobs:
  - job: 'Test'
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 4

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: |
          python -m pip install --upgrade pip
          pip install pycodestyle asyncpg coverage codecov
          pip install .
        displayName: 'Install dependencies'

      - script: |
          python -m unittest -v
          pycodestyle cr8
        displayName: 'test'

  - job: 'Publish'
    dependsOn: 'Test'
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          architecture: 'x64'

      - script: python setup.py sdist
        displayName: 'Build sdist'
